/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
    Mesh001: THREE.Mesh
    Mesh001_1: THREE.Mesh
  }
  materials: {
    ColorMaterial: THREE.MeshStandardMaterial
    TextureMaterial: THREE.MeshStandardMaterial
  }
}

export default function TShirts(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/t-shirts.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-7.75, 0, 0]}>
        <mesh
          material={materials.ColorMaterial}
          geometry={nodes.Mesh.geometry}
        />
        <mesh
          material={materials.TextureMaterial}
          geometry={nodes.Mesh_1.geometry}
        />
      </group>
      <mesh
        material={materials.ColorMaterial}
        geometry={nodes.Mesh001.geometry}
      />
      <mesh
        material={materials.TextureMaterial}
        geometry={nodes.Mesh001_1.geometry}
      />
    </group>
  )
}

useGLTF.preload('/t-shirts.glb')
