/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useFrame } from 'react-three-fiber'

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh
    Text003: THREE.Mesh
    Circle001: THREE.Mesh
    Text005: THREE.Mesh
    Text006: THREE.Mesh
    Cone: THREE.Mesh
    Text007: THREE.Mesh
    Text008: THREE.Mesh
  }
  materials: {
    Red: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
  }
}

export default function WebGL(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/WebGL.glb') as GLTFResult
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    if (group.current) {
      group.current.rotation.z = (1 + Math.sin(t / 1.5)) / 20
      group.current.rotation.x = Math.cos(t / 4) / 8
      group.current.rotation.y = Math.sin(t / 4) / 8
      group.current.position.y = (1 + Math.sin(t / 1.5)) / 10
    }
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.Red} geometry={nodes.Circle.geometry}>
        <mesh
          material={materials.Red}
          geometry={nodes.Text003.geometry}
          position={[-1, -0.33, 0.24]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/WebGL.glb')
